### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [milosgajdos/tenus#27]
I found that this project already [supports Go modules](https://github.com/milosgajdos/tenus/blob/master/go.mod). But sadly, the [tags](https://github.com/milosgajdos/tenus/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/milosgajdos/tenus v0.0.0-20200730100109-997445a7a4dd
```
Else the mod file shows something like `github.com/milosgajdos/tenus v0.0.0-20200730100109-997445a7a4dd` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@alrs  @YuviGold  Could you help me review this issue? Thx :p

**Comment by milosgajdos** [comment]
Hi @KateGo520, I'm happy to do this. I guess maybe we can kick this off with `v0.0.1` release. WDYT?

**Comment by KateGo520** [comment]
@milosgajdos  I think it's a good idea.

**Comment by milosgajdos** [comment]
This should now be [done](https://github.com/milosgajdos/tenus/releases/tag/v0.0.3).
