### ISSUE TITLE
Interact with wifi interfaces

### ISSUE THREAD

**Issue by lakinduakash** [milosgajdos/tenus#28]
This is not exactly an issue. However, I want to know whether this library is able to create virtual wifi interfaces and bridge them with networks. Thanks in adavance.

**Comment by milosgajdos** [comment]
I think that should be possible -- mind you, I haven't tried that, but I think of any reason why this wouldn't work 🤔

**Comment by lakinduakash** [comment]
Thanks for the reply. Actually, I haven't gone through in-depth of the library. I'm planning to integrate this to [linux-wifi-hotspot](https://github.com/lakinduakash/linux-wifi-hotspot) project. It is currently using a bash script to provision Wifi interfaces and all.
